=== dudochkin-victor/touch-inputmethodkeyboard/m-keyboard/layouts/VirtualKeyboardLayout.dtd
<!ELEMENT keyboard (layout | import)*>
<!ELEMENT import EMPTY>
<!ELEMENT layout (section+)>
<!ELEMENT section (row+)>
<!ELEMENT row (key | spacer)*>
<!ELEMENT key (binding+)>
<!ELEMENT spacer EMPTY>
<!ELEMENT binding EMPTY>

<!ATTLIST keyboard
  version CDATA "1.0"
  title CDATA #IMPLIED
  language CDATA #IMPLIED
  catalog CDATA #IMPLIED
  autocapitalization (true | false) "true">

<!ATTLIST import
  file CDATA #REQUIRED>

<!ATTLIST layout
  type (general | url | email | number | phonenumber | common) "general"
  orientation (landscape | portrait) "landscape">

<!ATTLIST section
  id CDATA #REQUIRED
  movable (true | false) "true"
  type (sloppy | non-sloppy) "sloppy">

<!ATTLIST row
  height (small | medium | large | x-large | xx-large) "medium"
  fixed (true | false) "false">

<!ATTLIST key
  style (normal | special | deadkey) "normal"
  width (small | medium | large | x-large | xx-large | stretched) "medium"
  fixed (true | false) "false"
  rtl (true | false) "false"
  id CDATA #IMPLIED
>

<!ATTLIST binding
  action (insert | shift | backspace | space | cycle | layout_menu | sym
          | return | commit | decimal_separator | plus_minus_toggle | switch) "insert"
  shift (true|false) "false"
  alt (true|false) "false"
  label CDATA #IMPLIED
  secondary_label CDATA #IMPLIED
  accents CDATA #IMPLIED
  accented_labels CDATA #IMPLIED
  extended_labels CDATA #IMPLIED
  cycleset CDATA #IMPLIED
  dead (true | false) "false"
  quickpick (true | false) "false">

=== dudochkin-victor/touch-inputmethodkeyboard/tests/ut_mimabstractkeyarea/layouts/test-import2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="test-import2-title" version="1.0" catalog="en_GB" language="test-import2-language" >
  <layout type="general" orientation="portrait" >
    <section id="main" type="sloppy" movable="false">
      <row>
        <key>
          <binding label="2" />
        </key>
      </row>
      <row>
        <key>
          <binding label="func2" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== dudochkin-victor/touch-inputmethodkeyboard/m-keyboard/layouts/hwsymbols_common.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" catalog="symbols">
    <layout type="general" orientation="landscape">
        <section id="symbols0" type="non-sloppy" movable="false">
          <row>
            <key>
              <binding label="&#x0026;"/>
            </key>
            <key>
              <binding label="¿"/>
            </key>
            <key>
              <binding label="¡"/>
            </key>
            <key>
              <binding label="="/>
            </key>
            <key>
              <binding label="&#x005C;"/>
            </key>
            <key>
              <binding label="_"/>
            </key>
            <key>
              <binding label="~"/>
            </key>
            <key>
              <binding label="|"/>
            </key>
            <key>
              <binding label="^"/>
            </key>
            <key>
              <binding label="`"/>
            </key>
          </row>

          <row>
            <key>
              <binding label="€"/>
            </key>
            <key>
              <binding label="£"/>
            </key>
            <key>
              <binding label="$"/>
            </key>
            <key>
              <binding label="¥"/>
            </key>
            <key>
              <binding label="&#x2018;"/>
            </key>
            <key>
              <binding label="&#x0022;"/>
            </key>
            <key>
              <binding label="&#x201C;"/>
            </key>
            <key>
              <binding label="&#x201D;"/>
            </key>
            <key>
              <binding label="&#x201E;"/>
            </key>
            <key>
              <binding label="&#x201F;"/>
            </key>
          </row>

          <row>
            <key>
              <binding label="%"/>
            </key>
            <key>
              <binding label="&#x2030;"/>
            </key>
            <key>
              <binding label="&#x003C;"/>
            </key>
            <key>
              <binding label="&#x003E;"/>
            </key>
            <key>
              <binding label="«"/>
            </key>
            <key>
              <binding label="»"/>
            </key>
            <key>
              <binding label="["/>
            </key>
            <key>
              <binding label="]"/>
            </key>
            <key>
              <binding label="{"/>
            </key>
            <key>
              <binding label="}"/>
            </key>
          </row>
        </section>
    </layout>
</keyboard>

=== dudochkin-victor/touch-inputmethodkeyboard/tests/ut_mimabstractkeyarea/layouts/test-layout.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Español" version="1.0" catalog="es" language="es">
    <layout type="general" orientation="landscape">
        <section id="main" movable="false">
          <row>
            <key>
              <binding label="q"/>
              <binding shift="true" label="Q"/>
            </key>
            <key>
              <binding label="w"/>
              <binding shift="true" label="W"/>
            </key>
            <key>
              <binding accented_labels="éë" accents="´¨" label="e"
                       extended_labels="êè"/>
              <binding shift="true" accented_labels="ÉË" accents="´¨" label="E"
                       extended_labels="ÊÈ"/>
            </key>
            <key>
              <binding label="r"/>
              <binding shift="true" label="R"/>
            </key>
            <key>
              <binding label="t"/>
              <binding shift="true" label="T"/>
            </key>
            <key>
              <binding accented_labels="ýÿ" accents="´¨" label="y"/>
              <binding shift="true" accented_labels="ÝŸ" accents="´¨" label="Y"/>
            </key>
            <key>
              <binding accented_labels="úü" accents="´¨" label="u"/>
              <binding shift="true" accented_labels="ÚÜ" accents="´¨" label="U"/>
            </key>
            <key>
              <binding accented_labels="íï" accents="´¨" label="i"/>
              <binding shift="true" accented_labels="ÍÏ" accents="´¨" label="I"/>
            </key>
            <key>
              <binding accented_labels="óö" accents="´¨" label="o"/>
              <binding shift="true" accented_labels="ÓÖ" accents="´¨" label="O"/>
            </key>
            <key id="actionKey">
              <binding label="p"/>
              <binding shift="true" label="P"/>
            </key>
          </row>
          <row>
            <key>
              <binding accented_labels="áä" accents="´¨" label="a"/>
              <binding shift="true" accented_labels="ÁÄ" accents="´¨" label="A"/>
            </key>
            <key>
              <binding label="s"/>
              <binding shift="true" label="S"/>
            </key>
            <key>
              <binding label="d"/>
              <binding shift="true" label="D"/>
            </key>
            <key>
              <binding label="f"/>
              <binding shift="true" label="F"/>
            </key>
            <key>
              <binding label="g"/>
              <binding shift="true" label="G"/>
            </key>
            <key>
              <binding label="h"/>
              <binding shift="true" label="H"/>
            </key>
            <key>
              <binding label="j"/>
              <binding shift="true" label="J"/>
            </key>
            <key>
              <binding label="k"/>
              <binding shift="true" label="K"/>
            </key>
            <key>
              <binding label="l"/>
              <binding shift="true" label="L"/>
            </key>
            <key>
              <binding label="ñ"/>
              <binding shift="true" label="Ñ"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="z"/>
              <binding shift="true" label="Z"/>
            </key>
            <key>
              <binding label="x"/>
              <binding shift="true" label="X"/>
            </key>
            <key>
              <binding label="c"/>
              <binding shift="true" label="C"/>
            </key>
            <key>
              <binding label="v"/>
              <binding shift="true" label="V"/>
            </key>
            <key>
              <binding label="b"/>
              <binding shift="true" label="B"/>
            </key>
            <key>
              <binding label="n"/>
              <binding shift="true" label="N"/>
            </key>
            <key>
              <binding label="m"/>
              <binding shift="true" label="M"/>
            </key>
            <key>
              <binding label="ç"/>
              <binding shift="true" label="Ç"/>
            </key>
            <key>
              <binding dead="true" label="´"/>
              <binding shift="true" dead="true" label="¨"/>
            </key>
            <key>
              <binding action="backspace" label=""/>
            </key>
          </row>
          <row>
            <key>
              <binding action="shift" label=""/>
            </key>
            <key>
              <binding action="sym" label="Sym" secondary_label="áçè"/>
              <binding shift="true" action="layout_menu" label=""/>
            </key>
            <key>
              <binding label="!"/>
              <binding shift="true" label="¡"/>
            </key>
            <key>
              <binding action="space" label=""/>
            </key>
            <key>
              <binding label="?"/>
              <binding shift="true" label="¿"/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label=","/>
            </key>
            <key id="actionKey">
              <binding action="return" label=""/>
            </key>
          </row>
        </section>
    </layout>
</keyboard>

=== dudochkin-victor/touch-inputmethodkeyboard/m-keyboard/layouts/phonenumber.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="Phone Number" language="phonenumber" catalog="phonenumber">
  <layout type="phonenumber" orientation="landscape">
    <section id="main" movable="false" >
      <row height="x-large">
        <key>
          <binding label="1"/>
        </key>
        <key>
          <binding label="2" secondary_label="abc"/>
        </key>
        <key>
          <binding label="3" secondary_label="def"/>
        </key>
        <key>
          <binding label="4" secondary_label="ghi"/>
        </key>
        <key>
          <binding label="5" secondary_label="jkl"/>
        </key>
        <key>
          <binding label="6" secondary_label="mno"/>
        </key>
        <key>
          <binding label="7" secondary_label="pqrs"/>
        </key>
        <key>
          <binding label="8" secondary_label="tuv"/>
        </key>
        <key>
          <binding label="9" secondary_label="wxyz"/>
        </key>
        <key>
          <binding label="0"/>
        </key>
      </row>

      <row>
        <spacer/>

        <key width="x-large">
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key width="x-large">
          <binding label="&#x0023;"/>
        </key>
        <key style="special" width="x-large">
          <binding label="" action="backspace"/>
        </key>
      </row>
    </section>
  </layout>

  <layout type="phonenumber" orientation="portrait">
    <section id="main" movable="false" >
      <row>
        <key>
          <binding label="1"/>
        </key>
        <key>
          <binding label="2" secondary_label="abc"/>
        </key>
        <key>
          <binding label="3" secondary_label="def"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="4" secondary_label="ghi"/>
        </key>
        <key>
          <binding label="5" secondary_label="jkl"/>
        </key>
        <key>
          <binding label="6" secondary_label="mno"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="7" secondary_label="pqrs"/>
        </key>
        <key>
          <binding label="8" secondary_label="tuv"/>
        </key>
        <key>
          <binding label="9" secondary_label="wxyz"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key>
          <binding label="0"/>
        </key>
        <key>
          <binding label="&#x0023;"/>
        </key>
      </row>

      <row>
        <spacer/>

        <key style="special" width="x-large">
          <binding label="" action="backspace"/>
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== dudochkin-victor/touch-inputmethodkeyboard/m-keyboard/layouts/phonenumber_ar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="Phone Number" language="phonenumber" catalog="phonenumber">
  <layout type="phonenumber" orientation="landscape">
    <section id="main" movable="false">
      <row height="x-large">
        <key>
          <binding label="&#x0661;"/>
        </key>
        <key>
          <binding label="&#x0662;" secondary_label="&#x0628;&#x062A;&#x0629;&#x062B;"/>
        </key>
        <key>
          <binding label="&#x0663;" secondary_label="&#x0627;&#x0621;"/>
        </key>
        <key>
          <binding label="&#x0664;" secondary_label="&#x0633;&#x0634;&#x0635;&#x0636;"/>
        </key>
        <key>
          <binding label="&#x0665;" secondary_label="&#x062F;&#x0630;&#x0631;&#x0632;"/>
        </key>
        <key>
          <binding label="&#x0666;" secondary_label="&#x062C;&#x062D;&#x062E;"/>
        </key>
        <key>
          <binding label="&#x0667;" secondary_label="&#x0646;&#x0647;&#x0648;&#x064A;"/>
        </key>
        <key>
          <binding label="&#x0668;" secondary_label="&#x0641;&#x0642;&#x0643;&#x0644;&#x0645;"/>
        </key>
        <key>
          <binding label="&#x0669;" secondary_label="&#x0637;&#x0638;&#x0639;&#x063A;"/>
        </key>
        <key>
          <binding label="&#x0660;"/>
        </key>
      </row>

      <row>
        <spacer/>

        <key>
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key>
          <binding label="&#x0023;"/>
        </key>
        <key style="special" width="x-large">
          <binding label="" action="backspace"/>
        </key>
      </row>
    </section>
  </layout>

  <layout type="phonenumber" orientation="portrait">
    <section id="main" movable="false">
      <row>
        <key>
          <binding label="&#x0661;"/>
        </key>
        <key>
          <binding label="&#x0662;" secondary_label="&#x0628;&#x062A;&#x0629;&#x062B;"/>
        </key>
        <key>
          <binding label="&#x0663;" secondary_label="&#x0627;&#x0621;"/>
        </key>
      </row>

      <row> 
        <key>
          <binding label="&#x0664;" secondary_label="&#x0633;&#x0634;&#x0635;&#x0636;"/>
        </key>
        <key>
          <binding label="&#x0665;" secondary_label="&#x062F;&#x0630;&#x0631;&#x0632;"/>
        </key>
        <key>
          <binding label="&#x0666;" secondary_label="&#x062C;&#x062D;&#x062E;"/>
        </key>
      </row>

      <row> 
        <key>
          <binding label="&#x0667;" secondary_label="&#x0646;&#x0647;&#x0648;&#x064A;"/>
        </key>
        <key>
          <binding label="&#x0668;" secondary_label="&#x0641;&#x0642;&#x0643;&#x0644;&#x0645;"/>
        </key>
        <key>
          <binding label="&#x0669;" secondary_label="&#x0637;&#x0638;&#x0639;&#x063A;"/>
        </key>
      </row>

      <row> 
        <key>
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key>
          <binding label="&#x0660;"/>
        </key>
        <key>
          <binding label="&#x0023;"/>
        </key>
      </row>

      <row> 
        <spacer/>

        <key style="special" width="x-large">
          <binding label="" action="backspace"/>
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== dudochkin-victor/touch-inputmethodkeyboard/tests/ut_symbolview/testsymbols.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" catalog="symbols">
  <layout type="general" orientation="landscape">
    <section id="symbols0" type="non-sloppy">
      <row>
        <spacer/>
        <key>
          <binding label="@" quickpick="true"/>
        </key>
        <key>
          <binding label="~"/>
        </key>
        <key>
          <binding label="&#x0027;" quickpick="true"/>
        </key>
        <key>
          <binding label="&#x003B;"/>
        </key>
        <key>
          <binding label="&#x003A;"/>
        </key>
        <spacer/>
      </row>
    </section>

    <section id="symbols1" type="non-sloppy">
      <row>
        <key>
          <binding label="u"/>
        </key>
        <key>
          <binding label="p"/>
        </key>
        <key>
          <binding label="p"/>
        </key>
        <key>
          <binding label="e"/>
        </key>
        <key>
          <binding label="r"/>
        </key>
      </row>
      <row>
        <spacer/>
        <key>
          <binding label="&#x003C;"/>
        </key>
        <key>
          <binding label="&#x003E;"/>
        </key>
        <spacer/>
      </row>
    </section>
  </layout>
</keyboard>

=== dudochkin-victor/touch-inputmethodkeyboard/m-keyboard/layouts/number_ar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="Number" language="number" catalog="number">
  <layout type="number" orientation="landscape">
    <section id="main" movable="false" horizontal_alignment="center" vertical_alignment="center">
      <row>
        <key>
          <binding label="&#x0661;"/>
        </key>
        <key>
          <binding label="&#x0662;"/>
        </key>
        <key>
          <binding label="&#x0663;"/>
        </key>
        <key>
          <binding label="&#x0664;"/>
        </key>
        <key>
          <binding label="&#x0665;"/>
        </key>
        <key>
          <binding label="&#x0666;"/>
        </key>
        <key>
          <binding label="&#x0667;"/>
        </key>
        <key>
          <binding label="&#x0668;"/>
        </key>
        <key>
          <binding label="&#x0669;"/>
        </key>
        <key>
          <binding label="&#x0660;"/>
        </key>
      </row>
      <row>
        <spacer/>

        <key width="x-large">
          <binding label="&#x002B;&#x002F;&#x002D;" action="plus_minus_toggle"/>
        </key>
        <key width="x-large">
          <binding action="decimal_separator"/>
        </key>
        <key style="special" width="x-large" rtl="true">
          <binding label="" action="backspace"/>
        </key>
      </row>
    </section>
  </layout>

  <layout type="number" orientation="portrait">
    <section id="main" movable="false" horizontal_alignment="center" vertical_alignment="center">
      <row>
        <key>
          <binding label="&#x0661;"/>
        </key>
        <key>
          <binding label="&#x0662;"/>
        </key>
        <key>
          <binding label="&#x0663;"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="&#x0664;"/>
        </key>
        <key>
          <binding label="&#x0665;"/>
        </key>
        <key>
          <binding label="&#x0666;"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="&#x0667;"/>
        </key>
        <key>
          <binding label="&#x0668;"/>
        </key>
        <key>
          <binding label="&#x0669;"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="&#x002B;&#x002F;&#x002D;" action="plus_minus_toggle"/>
        </key>
        <key>
          <binding label="&#x0660;"/>
        </key>
        <key>
          <binding action="decimal_separator"/>
        </key>
      </row>

      <row>
        <spacer/>

        <key style="special" width="x-large" rtl="true">
          <binding label="" action="backspace"/>
        </key>
      </row>
    </section>
  </layout>
</keyboard>
